//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.18 at 05:12:25 PM MST 
//


package org.sgs.sandbox.controlm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for DOMAILType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DOMAILType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="ATTACH_SYSOUT" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="DEST" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="MESSAGE" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="SUBJECT" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="URGENCY" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="CC_DEST" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ACTION" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DOMAILType", propOrder = {
    "value"
})
public class DOMAILType {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "ATTACH_SYSOUT")
    protected String attachsysout;
    @XmlAttribute(name = "DEST")
    protected String dest;
    @XmlAttribute(name = "MESSAGE")
    protected String message;
    @XmlAttribute(name = "SUBJECT")
    protected String subject;
    @XmlAttribute(name = "URGENCY")
    protected String urgency;
    @XmlAttribute(name = "CC_DEST")
    protected String ccdest;
    @XmlAttribute(name = "ACTION")
    protected String action;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the attachsysout property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getATTACHSYSOUT() {
        return attachsysout;
    }

    /**
     * Sets the value of the attachsysout property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setATTACHSYSOUT(String value) {
        this.attachsysout = value;
    }

    /**
     * Gets the value of the dest property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDEST() {
        return dest;
    }

    /**
     * Sets the value of the dest property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDEST(String value) {
        this.dest = value;
    }

    /**
     * Gets the value of the message property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMESSAGE() {
        return message;
    }

    /**
     * Sets the value of the message property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMESSAGE(String value) {
        this.message = value;
    }

    /**
     * Gets the value of the subject property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSUBJECT() {
        return subject;
    }

    /**
     * Sets the value of the subject property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSUBJECT(String value) {
        this.subject = value;
    }

    /**
     * Gets the value of the urgency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getURGENCY() {
        return urgency;
    }

    /**
     * Sets the value of the urgency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setURGENCY(String value) {
        this.urgency = value;
    }

    /**
     * Gets the value of the ccdest property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCCDEST() {
        return ccdest;
    }

    /**
     * Sets the value of the ccdest property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCCDEST(String value) {
        this.ccdest = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACTION() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACTION(String value) {
        this.action = value;
    }

}
