//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.18 at 05:12:25 PM MST 
//


package org.sgs.sandbox.controlm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for INCONDType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="INCONDType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="AND_OR" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="NAME" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ODATE" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="OP" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "INCONDType", propOrder = {
    "value"
})
public class INCONDType {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "AND_OR")
    protected String andor;
    @XmlAttribute(name = "NAME")
    protected String name;
    @XmlAttribute(name = "ODATE")
    protected String odate;
    @XmlAttribute(name = "OP")
    protected String op;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the andor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getANDOR() {
        return andor;
    }

    /**
     * Sets the value of the andor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setANDOR(String value) {
        this.andor = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNAME() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNAME(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the odate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getODATE() {
        return odate;
    }

    /**
     * Sets the value of the odate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setODATE(String value) {
        this.odate = value;
    }

    /**
     * Gets the value of the op property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOP() {
        return op;
    }

    /**
     * Sets the value of the op property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOP(String value) {
        this.op = value;
    }

}
