//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.18 at 05:12:25 PM MST 
//


package org.sgs.sandbox.controlm;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for JOBType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="JOBType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="INCOND" type="{}INCONDType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="QUANTITATIVE" type="{}QUANTITATIVEType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="OUTCOND" type="{}OUTCONDType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="AUTOEDIT2" type="{}AUTOEDIT2Type" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SHOUT" type="{}SHOUTType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ON" type="{}ONType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="JAN" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="FEB" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="MAR" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="APR" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="MAY" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="JUN" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="JUL" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="AUG" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="SEP" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="OCT" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="NOV" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="DEC" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="APPLICATION" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="APPL_FORM" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="APPL_TYPE" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="APPL_VER" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="AUTHOR" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="AUTOARCH" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="CHANGE_DATE" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="CHANGE_TIME" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="CHANGE_USERID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="CM_VER" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="CONFIRM" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="CREATION_DATE" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="CREATION_TIME" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="CREATION_USER" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="CRITICAL" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="CYCLIC" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="CYCLIC_INTERVAL_SEQUENCE" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="CYCLIC_TYPE" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="DAYS_AND_OR" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="DESCRIPTION" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="GROUP" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="IND_CYCLIC" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="INTERVAL" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="JOBNAME" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="MAXDAYS" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="MAXRERUN" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="MAXRUNS" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="MAXWAIT" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="MEMLIB" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="MEMNAME" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="MULTY_AGENT" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="NODEID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="OWNER" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="PARENT_TABLE" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="RETRO" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="RULE_BASED_CALENDAR_RELATIONSHIP" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="SHIFT" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="SHIFTNUM" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="SYSDB" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="TASKTYPE" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="USE_INSTREAM_JCL" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="WEEKDAYS" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="CMDLINE" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="DAYSCAL" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="WEEKSCAL" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="TIMEFROM" type="{http://www.w3.org/2001/XMLSchema}short" />
 *       &lt;attribute name="TIMETO" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="CONFCAL" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ACTIVE_FROM" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="DAYS" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="DATE" type="{http://www.w3.org/2001/XMLSchema}short" />
 *       &lt;attribute name="PRIORITY" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "JOBType", propOrder = {
    "incond",
    "quantitative",
    "outcond",
    "autoedit2",
    "shout",
    "on"
})
public class JOBType {

    @XmlElement(name = "INCOND")
    protected List<INCONDType> incond;
    @XmlElement(name = "QUANTITATIVE")
    protected List<QUANTITATIVEType> quantitative;
    @XmlElement(name = "OUTCOND")
    protected List<OUTCONDType> outcond;
    @XmlElement(name = "AUTOEDIT2")
    protected List<AUTOEDIT2Type> autoedit2;
    @XmlElement(name = "SHOUT")
    protected List<SHOUTType> shout;
    @XmlElement(name = "ON")
    protected List<ONType> on;
    @XmlAttribute(name = "JAN")
    protected Byte jan;
    @XmlAttribute(name = "FEB")
    protected Byte feb;
    @XmlAttribute(name = "MAR")
    protected Byte mar;
    @XmlAttribute(name = "APR")
    protected Byte apr;
    @XmlAttribute(name = "MAY")
    protected Byte may;
    @XmlAttribute(name = "JUN")
    protected Byte jun;
    @XmlAttribute(name = "JUL")
    protected Byte jul;
    @XmlAttribute(name = "AUG")
    protected Byte aug;
    @XmlAttribute(name = "SEP")
    protected Byte sep;
    @XmlAttribute(name = "OCT")
    protected Byte oct;
    @XmlAttribute(name = "NOV")
    protected Byte nov;
    @XmlAttribute(name = "DEC")
    protected Byte dec;
    @XmlAttribute(name = "APPLICATION")
    protected String application;
    @XmlAttribute(name = "APPL_FORM")
    protected String applform;
    @XmlAttribute(name = "APPL_TYPE")
    protected String appltype;
    @XmlAttribute(name = "APPL_VER")
    protected String applver;
    @XmlAttribute(name = "AUTHOR")
    protected String author;
    @XmlAttribute(name = "AUTOARCH")
    protected Byte autoarch;
    @XmlAttribute(name = "CHANGE_DATE")
    protected Integer changedate;
    @XmlAttribute(name = "CHANGE_TIME")
    protected Integer changetime;
    @XmlAttribute(name = "CHANGE_USERID")
    protected String changeuserid;
    @XmlAttribute(name = "CM_VER")
    protected String cmver;
    @XmlAttribute(name = "CONFIRM")
    protected Byte confirm;
    @XmlAttribute(name = "CREATION_DATE")
    protected Integer creationdate;
    @XmlAttribute(name = "CREATION_TIME")
    protected Integer creationtime;
    @XmlAttribute(name = "CREATION_USER")
    protected String creationuser;
    @XmlAttribute(name = "CRITICAL")
    protected Byte critical;
    @XmlAttribute(name = "CYCLIC")
    protected Byte cyclic;
    @XmlAttribute(name = "CYCLIC_INTERVAL_SEQUENCE")
    protected String cyclicintervalsequence;
    @XmlAttribute(name = "CYCLIC_TYPE")
    protected String cyclictype;
    @XmlAttribute(name = "DAYS_AND_OR")
    protected String daysandor;
    @XmlAttribute(name = "DESCRIPTION")
    protected String description;
    @XmlAttribute(name = "GROUP")
    protected String group;
    @XmlAttribute(name = "IND_CYCLIC")
    protected String indcyclic;
    @XmlAttribute(name = "INTERVAL")
    protected String interval;
    @XmlAttribute(name = "JOBNAME")
    protected String jobname;
    @XmlAttribute(name = "MAXDAYS")
    protected Byte maxdays;
    @XmlAttribute(name = "MAXRERUN")
    protected Byte maxrerun;
    @XmlAttribute(name = "MAXRUNS")
    protected Byte maxruns;
    @XmlAttribute(name = "MAXWAIT")
    protected Byte maxwait;
    @XmlAttribute(name = "MEMLIB")
    protected String memlib;
    @XmlAttribute(name = "MEMNAME")
    protected String memname;
    @XmlAttribute(name = "MULTY_AGENT")
    protected String multyagent;
    @XmlAttribute(name = "NODEID")
    protected String nodeid;
    @XmlAttribute(name = "OWNER")
    protected String owner;
    @XmlAttribute(name = "PARENT_TABLE")
    protected String parenttable;
    @XmlAttribute(name = "RETRO")
    protected Byte retro;
    @XmlAttribute(name = "RULE_BASED_CALENDAR_RELATIONSHIP")
    protected String rulebasedcalendarrelationship;
    @XmlAttribute(name = "SHIFT")
    protected String shift;
    @XmlAttribute(name = "SHIFTNUM")
    protected Byte shiftnum;
    @XmlAttribute(name = "SYSDB")
    protected Byte sysdb;
    @XmlAttribute(name = "TASKTYPE")
    protected String tasktype;
    @XmlAttribute(name = "USE_INSTREAM_JCL")
    protected String useinstreamjcl;
    @XmlAttribute(name = "WEEKDAYS")
    protected String weekdays;
    @XmlAttribute(name = "CMDLINE")
    protected String cmdline;
    @XmlAttribute(name = "DAYSCAL")
    protected String dayscal;
    @XmlAttribute(name = "WEEKSCAL")
    protected String weekscal;
    @XmlAttribute(name = "TIMEFROM")
    protected Short timefrom;
    @XmlAttribute(name = "TIMETO")
    protected String timeto;
    @XmlAttribute(name = "CONFCAL")
    protected String confcal;
    @XmlAttribute(name = "ACTIVE_FROM")
    protected Integer activefrom;
    @XmlAttribute(name = "DAYS")
    protected String days;
    @XmlAttribute(name = "DATE")
    protected Short date;
    @XmlAttribute(name = "PRIORITY")
    protected String priority;

    /**
     * Gets the value of the incond property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the incond property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getINCOND().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link INCONDType }
     * 
     * 
     */
    public List<INCONDType> getINCOND() {
        if (incond == null) {
            incond = new ArrayList<INCONDType>();
        }
        return this.incond;
    }

    /**
     * Gets the value of the quantitative property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the quantitative property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQUANTITATIVE().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link QUANTITATIVEType }
     * 
     * 
     */
    public List<QUANTITATIVEType> getQUANTITATIVE() {
        if (quantitative == null) {
            quantitative = new ArrayList<QUANTITATIVEType>();
        }
        return this.quantitative;
    }

    /**
     * Gets the value of the outcond property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the outcond property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOUTCOND().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OUTCONDType }
     * 
     * 
     */
    public List<OUTCONDType> getOUTCOND() {
        if (outcond == null) {
            outcond = new ArrayList<OUTCONDType>();
        }
        return this.outcond;
    }

    /**
     * Gets the value of the autoedit2 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the autoedit2 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAUTOEDIT2().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AUTOEDIT2Type }
     * 
     * 
     */
    public List<AUTOEDIT2Type> getAUTOEDIT2() {
        if (autoedit2 == null) {
            autoedit2 = new ArrayList<AUTOEDIT2Type>();
        }
        return this.autoedit2;
    }

    /**
     * Gets the value of the shout property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the shout property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSHOUT().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SHOUTType }
     * 
     * 
     */
    public List<SHOUTType> getSHOUT() {
        if (shout == null) {
            shout = new ArrayList<SHOUTType>();
        }
        return this.shout;
    }

    /**
     * Gets the value of the on property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the on property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getON().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ONType }
     * 
     * 
     */
    public List<ONType> getON() {
        if (on == null) {
            on = new ArrayList<ONType>();
        }
        return this.on;
    }

    /**
     * Gets the value of the jan property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getJAN() {
        return jan;
    }

    /**
     * Sets the value of the jan property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setJAN(Byte value) {
        this.jan = value;
    }

    /**
     * Gets the value of the feb property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getFEB() {
        return feb;
    }

    /**
     * Sets the value of the feb property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setFEB(Byte value) {
        this.feb = value;
    }

    /**
     * Gets the value of the mar property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getMAR() {
        return mar;
    }

    /**
     * Sets the value of the mar property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setMAR(Byte value) {
        this.mar = value;
    }

    /**
     * Gets the value of the apr property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getAPR() {
        return apr;
    }

    /**
     * Sets the value of the apr property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setAPR(Byte value) {
        this.apr = value;
    }

    /**
     * Gets the value of the may property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getMAY() {
        return may;
    }

    /**
     * Sets the value of the may property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setMAY(Byte value) {
        this.may = value;
    }

    /**
     * Gets the value of the jun property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getJUN() {
        return jun;
    }

    /**
     * Sets the value of the jun property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setJUN(Byte value) {
        this.jun = value;
    }

    /**
     * Gets the value of the jul property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getJUL() {
        return jul;
    }

    /**
     * Sets the value of the jul property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setJUL(Byte value) {
        this.jul = value;
    }

    /**
     * Gets the value of the aug property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getAUG() {
        return aug;
    }

    /**
     * Sets the value of the aug property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setAUG(Byte value) {
        this.aug = value;
    }

    /**
     * Gets the value of the sep property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getSEP() {
        return sep;
    }

    /**
     * Sets the value of the sep property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setSEP(Byte value) {
        this.sep = value;
    }

    /**
     * Gets the value of the oct property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getOCT() {
        return oct;
    }

    /**
     * Sets the value of the oct property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setOCT(Byte value) {
        this.oct = value;
    }

    /**
     * Gets the value of the nov property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getNOV() {
        return nov;
    }

    /**
     * Sets the value of the nov property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setNOV(Byte value) {
        this.nov = value;
    }

    /**
     * Gets the value of the dec property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getDEC() {
        return dec;
    }

    /**
     * Sets the value of the dec property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setDEC(Byte value) {
        this.dec = value;
    }

    /**
     * Gets the value of the application property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAPPLICATION() {
        return application;
    }

    /**
     * Sets the value of the application property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAPPLICATION(String value) {
        this.application = value;
    }

    /**
     * Gets the value of the applform property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAPPLFORM() {
        return applform;
    }

    /**
     * Sets the value of the applform property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAPPLFORM(String value) {
        this.applform = value;
    }

    /**
     * Gets the value of the appltype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAPPLTYPE() {
        return appltype;
    }

    /**
     * Sets the value of the appltype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAPPLTYPE(String value) {
        this.appltype = value;
    }

    /**
     * Gets the value of the applver property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAPPLVER() {
        return applver;
    }

    /**
     * Sets the value of the applver property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAPPLVER(String value) {
        this.applver = value;
    }

    /**
     * Gets the value of the author property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAUTHOR() {
        return author;
    }

    /**
     * Sets the value of the author property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAUTHOR(String value) {
        this.author = value;
    }

    /**
     * Gets the value of the autoarch property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getAUTOARCH() {
        return autoarch;
    }

    /**
     * Sets the value of the autoarch property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setAUTOARCH(Byte value) {
        this.autoarch = value;
    }

    /**
     * Gets the value of the changedate property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCHANGEDATE() {
        return changedate;
    }

    /**
     * Sets the value of the changedate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCHANGEDATE(Integer value) {
        this.changedate = value;
    }

    /**
     * Gets the value of the changetime property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCHANGETIME() {
        return changetime;
    }

    /**
     * Sets the value of the changetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCHANGETIME(Integer value) {
        this.changetime = value;
    }

    /**
     * Gets the value of the changeuserid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCHANGEUSERID() {
        return changeuserid;
    }

    /**
     * Sets the value of the changeuserid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCHANGEUSERID(String value) {
        this.changeuserid = value;
    }

    /**
     * Gets the value of the cmver property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCMVER() {
        return cmver;
    }

    /**
     * Sets the value of the cmver property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCMVER(String value) {
        this.cmver = value;
    }

    /**
     * Gets the value of the confirm property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getCONFIRM() {
        return confirm;
    }

    /**
     * Sets the value of the confirm property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setCONFIRM(Byte value) {
        this.confirm = value;
    }

    /**
     * Gets the value of the creationdate property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCREATIONDATE() {
        return creationdate;
    }

    /**
     * Sets the value of the creationdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCREATIONDATE(Integer value) {
        this.creationdate = value;
    }

    /**
     * Gets the value of the creationtime property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCREATIONTIME() {
        return creationtime;
    }

    /**
     * Sets the value of the creationtime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCREATIONTIME(Integer value) {
        this.creationtime = value;
    }

    /**
     * Gets the value of the creationuser property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCREATIONUSER() {
        return creationuser;
    }

    /**
     * Sets the value of the creationuser property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCREATIONUSER(String value) {
        this.creationuser = value;
    }

    /**
     * Gets the value of the critical property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getCRITICAL() {
        return critical;
    }

    /**
     * Sets the value of the critical property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setCRITICAL(Byte value) {
        this.critical = value;
    }

    /**
     * Gets the value of the cyclic property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getCYCLIC() {
        return cyclic;
    }

    /**
     * Sets the value of the cyclic property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setCYCLIC(Byte value) {
        this.cyclic = value;
    }

    /**
     * Gets the value of the cyclicintervalsequence property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCYCLICINTERVALSEQUENCE() {
        return cyclicintervalsequence;
    }

    /**
     * Sets the value of the cyclicintervalsequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCYCLICINTERVALSEQUENCE(String value) {
        this.cyclicintervalsequence = value;
    }

    /**
     * Gets the value of the cyclictype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCYCLICTYPE() {
        return cyclictype;
    }

    /**
     * Sets the value of the cyclictype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCYCLICTYPE(String value) {
        this.cyclictype = value;
    }

    /**
     * Gets the value of the daysandor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDAYSANDOR() {
        return daysandor;
    }

    /**
     * Sets the value of the daysandor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDAYSANDOR(String value) {
        this.daysandor = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDESCRIPTION() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDESCRIPTION(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the group property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGROUP() {
        return group;
    }

    /**
     * Sets the value of the group property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGROUP(String value) {
        this.group = value;
    }

    /**
     * Gets the value of the indcyclic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINDCYCLIC() {
        return indcyclic;
    }

    /**
     * Sets the value of the indcyclic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINDCYCLIC(String value) {
        this.indcyclic = value;
    }

    /**
     * Gets the value of the interval property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINTERVAL() {
        return interval;
    }

    /**
     * Sets the value of the interval property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINTERVAL(String value) {
        this.interval = value;
    }

    /**
     * Gets the value of the jobname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJOBNAME() {
        return jobname;
    }

    /**
     * Sets the value of the jobname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJOBNAME(String value) {
        this.jobname = value;
    }

    /**
     * Gets the value of the maxdays property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getMAXDAYS() {
        return maxdays;
    }

    /**
     * Sets the value of the maxdays property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setMAXDAYS(Byte value) {
        this.maxdays = value;
    }

    /**
     * Gets the value of the maxrerun property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getMAXRERUN() {
        return maxrerun;
    }

    /**
     * Sets the value of the maxrerun property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setMAXRERUN(Byte value) {
        this.maxrerun = value;
    }

    /**
     * Gets the value of the maxruns property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getMAXRUNS() {
        return maxruns;
    }

    /**
     * Sets the value of the maxruns property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setMAXRUNS(Byte value) {
        this.maxruns = value;
    }

    /**
     * Gets the value of the maxwait property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getMAXWAIT() {
        return maxwait;
    }

    /**
     * Sets the value of the maxwait property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setMAXWAIT(Byte value) {
        this.maxwait = value;
    }

    /**
     * Gets the value of the memlib property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMEMLIB() {
        return memlib;
    }

    /**
     * Sets the value of the memlib property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMEMLIB(String value) {
        this.memlib = value;
    }

    /**
     * Gets the value of the memname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMEMNAME() {
        return memname;
    }

    /**
     * Sets the value of the memname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMEMNAME(String value) {
        this.memname = value;
    }

    /**
     * Gets the value of the multyagent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMULTYAGENT() {
        return multyagent;
    }

    /**
     * Sets the value of the multyagent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMULTYAGENT(String value) {
        this.multyagent = value;
    }

    /**
     * Gets the value of the nodeid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNODEID() {
        return nodeid;
    }

    /**
     * Sets the value of the nodeid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNODEID(String value) {
        this.nodeid = value;
    }

    /**
     * Gets the value of the owner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOWNER() {
        return owner;
    }

    /**
     * Sets the value of the owner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOWNER(String value) {
        this.owner = value;
    }

    /**
     * Gets the value of the parenttable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPARENTTABLE() {
        return parenttable;
    }

    /**
     * Sets the value of the parenttable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPARENTTABLE(String value) {
        this.parenttable = value;
    }

    /**
     * Gets the value of the retro property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getRETRO() {
        return retro;
    }

    /**
     * Sets the value of the retro property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setRETRO(Byte value) {
        this.retro = value;
    }

    /**
     * Gets the value of the rulebasedcalendarrelationship property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRULEBASEDCALENDARRELATIONSHIP() {
        return rulebasedcalendarrelationship;
    }

    /**
     * Sets the value of the rulebasedcalendarrelationship property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRULEBASEDCALENDARRELATIONSHIP(String value) {
        this.rulebasedcalendarrelationship = value;
    }

    /**
     * Gets the value of the shift property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSHIFT() {
        return shift;
    }

    /**
     * Sets the value of the shift property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSHIFT(String value) {
        this.shift = value;
    }

    /**
     * Gets the value of the shiftnum property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getSHIFTNUM() {
        return shiftnum;
    }

    /**
     * Sets the value of the shiftnum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setSHIFTNUM(Byte value) {
        this.shiftnum = value;
    }

    /**
     * Gets the value of the sysdb property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getSYSDB() {
        return sysdb;
    }

    /**
     * Sets the value of the sysdb property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setSYSDB(Byte value) {
        this.sysdb = value;
    }

    /**
     * Gets the value of the tasktype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTASKTYPE() {
        return tasktype;
    }

    /**
     * Sets the value of the tasktype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTASKTYPE(String value) {
        this.tasktype = value;
    }

    /**
     * Gets the value of the useinstreamjcl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUSEINSTREAMJCL() {
        return useinstreamjcl;
    }

    /**
     * Sets the value of the useinstreamjcl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUSEINSTREAMJCL(String value) {
        this.useinstreamjcl = value;
    }

    /**
     * Gets the value of the weekdays property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWEEKDAYS() {
        return weekdays;
    }

    /**
     * Sets the value of the weekdays property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWEEKDAYS(String value) {
        this.weekdays = value;
    }

    /**
     * Gets the value of the cmdline property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCMDLINE() {
        return cmdline;
    }

    /**
     * Sets the value of the cmdline property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCMDLINE(String value) {
        this.cmdline = value;
    }

    /**
     * Gets the value of the dayscal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDAYSCAL() {
        return dayscal;
    }

    /**
     * Sets the value of the dayscal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDAYSCAL(String value) {
        this.dayscal = value;
    }

    /**
     * Gets the value of the weekscal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWEEKSCAL() {
        return weekscal;
    }

    /**
     * Sets the value of the weekscal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWEEKSCAL(String value) {
        this.weekscal = value;
    }

    /**
     * Gets the value of the timefrom property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getTIMEFROM() {
        return timefrom;
    }

    /**
     * Sets the value of the timefrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setTIMEFROM(Short value) {
        this.timefrom = value;
    }

    /**
     * Gets the value of the timeto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTIMETO() {
        return timeto;
    }

    /**
     * Sets the value of the timeto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTIMETO(String value) {
        this.timeto = value;
    }

    /**
     * Gets the value of the confcal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCONFCAL() {
        return confcal;
    }

    /**
     * Sets the value of the confcal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCONFCAL(String value) {
        this.confcal = value;
    }

    /**
     * Gets the value of the activefrom property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getACTIVEFROM() {
        return activefrom;
    }

    /**
     * Sets the value of the activefrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setACTIVEFROM(Integer value) {
        this.activefrom = value;
    }

    /**
     * Gets the value of the days property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDAYS() {
        return days;
    }

    /**
     * Sets the value of the days property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDAYS(String value) {
        this.days = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getDATE() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setDATE(Short value) {
        this.date = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPRIORITY() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPRIORITY(String value) {
        this.priority = value;
    }

}
