//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.18 at 05:12:25 PM MST 
//


package org.sgs.sandbox.controlm;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TABLEType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TABLEType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="JOB" type="{}JOBType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="DATACENTER" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="TABLE_NAME" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="USED_BY_CODE" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="TABLE_USERDAILY" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TABLEType", propOrder = {
    "job"
})
public class TABLEType {

    @XmlElement(name = "JOB")
    protected List<JOBType> job;
    @XmlAttribute(name = "DATACENTER")
    protected String datacenter;
    @XmlAttribute(name = "TABLE_NAME")
    protected String tablename;
    @XmlAttribute(name = "USED_BY_CODE")
    protected Byte usedbycode;
    @XmlAttribute(name = "TABLE_USERDAILY")
    protected String tableuserdaily;

    /**
     * Gets the value of the job property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the job property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getJOB().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JOBType }
     * 
     * 
     */
    public List<JOBType> getJOB() {
        if (job == null) {
            job = new ArrayList<JOBType>();
        }
        return this.job;
    }

    /**
     * Gets the value of the datacenter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDATACENTER() {
        return datacenter;
    }

    /**
     * Sets the value of the datacenter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDATACENTER(String value) {
        this.datacenter = value;
    }

    /**
     * Gets the value of the tablename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTABLENAME() {
        return tablename;
    }

    /**
     * Sets the value of the tablename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTABLENAME(String value) {
        this.tablename = value;
    }

    /**
     * Gets the value of the usedbycode property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getUSEDBYCODE() {
        return usedbycode;
    }

    /**
     * Sets the value of the usedbycode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setUSEDBYCODE(Byte value) {
        this.usedbycode = value;
    }

    /**
     * Gets the value of the tableuserdaily property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTABLEUSERDAILY() {
        return tableuserdaily;
    }

    /**
     * Sets the value of the tableuserdaily property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTABLEUSERDAILY(String value) {
        this.tableuserdaily = value;
    }

}
