//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.18 at 05:12:25 PM MST 
//


package org.sgs.controlm;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.sgs.sandbox.controlm package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DEFTABLE_QNAME = new QName("", "DEFTABLE");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.sgs.sandbox.controlm
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DEFTABLEType }
     * 
     */
    public DEFTABLEType createDEFTABLEType() {
        return new DEFTABLEType();
    }

    /**
     * Create an instance of {@link TABLEType }
     * 
     */
    public TABLEType createTABLEType() {
        return new TABLEType();
    }

    /**
     * Create an instance of {@link DOREMEDYType }
     * 
     */
    public DOREMEDYType createDOREMEDYType() {
        return new DOREMEDYType();
    }

    /**
     * Create an instance of {@link DOCONDType }
     * 
     */
    public DOCONDType createDOCONDType() {
        return new DOCONDType();
    }

    /**
     * Create an instance of {@link DOType }
     * 
     */
    public DOType createDOType() {
        return new DOType();
    }

    /**
     * Create an instance of {@link JOBType }
     * 
     */
    public JOBType createJOBType() {
        return new JOBType();
    }

    /**
     * Create an instance of {@link INCONDType }
     * 
     */
    public INCONDType createINCONDType() {
        return new INCONDType();
    }

    /**
     * Create an instance of {@link AUTOEDIT2Type }
     * 
     */
    public AUTOEDIT2Type createAUTOEDIT2Type() {
        return new AUTOEDIT2Type();
    }

    /**
     * Create an instance of {@link QUANTITATIVEType }
     * 
     */
    public QUANTITATIVEType createQUANTITATIVEType() {
        return new QUANTITATIVEType();
    }

    /**
     * Create an instance of {@link ONType }
     * 
     */
    public ONType createONType() {
        return new ONType();
    }

    /**
     * Create an instance of {@link OUTCONDType }
     * 
     */
    public OUTCONDType createOUTCONDType() {
        return new OUTCONDType();
    }

    /**
     * Create an instance of {@link DOMAILType }
     * 
     */
    public DOMAILType createDOMAILType() {
        return new DOMAILType();
    }

    /**
     * Create an instance of {@link SHOUTType }
     * 
     */
    public SHOUTType createSHOUTType() {
        return new SHOUTType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DEFTABLEType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DEFTABLE")
    public JAXBElement<DEFTABLEType> createDEFTABLE(DEFTABLEType value) {
        return new JAXBElement<DEFTABLEType>(_DEFTABLE_QNAME, DEFTABLEType.class, null, value);
    }

}
